name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install client dependencies and build
        run: |
          cd client
          yarn install
          yarn build

      - name: Build and make Electron app
        run: |
          cd server
          yarn install
          yarn build
          yarn make

      - name: Get version from package.json
        id: get_version
        run: |
          echo "VERSION=$(node -p "require('./server/package.json').version")" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PUSH_RELEASE_TOKEN }}
          draft: false
          prerelease: false
          tag_name: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          body: "Release of GCCU - Game Clip Cutting Utility."
          files: |
            server/out/make/squirrel.windows/x64/*
